linters:
  disable-all: true
  enable:
    - gofumpt
    - govet
    - gci
    - staticcheck
    - paralleltest

run:
  skip-dirs:
    - sing-box/transport/simple-obfs
    - sing-box/transport/clashssr
    - sing-boxtransport/cloudflaretls
    - sing-box/transport/shadowtls/tls
    - sing-box/transport/shadowtls/tls_go119

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/sagernet/)
      - prefix(github.com/xchacha20-poly1305/)
      - default
  staticcheck:
    go: '1.20'
