name: Lint

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "libs/**"
      - ".github/**"
      - "!.github/workflows/lint.yml"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=30m
          install-mode: binary
